"""After Configurattion2

Revision ID: 89834d34e7b8
Revises: f0e982b8e78f
Create Date: 2024-02-14 15:42:05.003941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89834d34e7b8'
down_revision = 'f0e982b8e78f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
